[versions]
# androidSdkVersions
compileSdkVersion = "35"
targetSdkVersion = "34"
minSdkVersion = "23"

# lint versions
lintApi = "31.6.1"
lintGradlePlugin = "8.6.1"

# gradlePlugin versions
androidGradlePlugin = "8.6.1"
apolloAdapters = "0.0.4"
apollo = "4.0.0"
cacheFix = "3.0.1"
crashlytics = "3.0.2"
datadogPlugin = "1.14.0"
doctor = "0.10.0"
easylauncher = "6.4.0"
googleServices = "4.4.2"
kotlin = "2.0.20"
kotlinter = "4.4.1"
ksp = "2.0.20-1.0.25"
ktor = "2.3.12"
license = "0.9.8"
molecule = "2.0.0"
squareSortDependencies = "0.8"

# Other versions sorted alphabetically
accompanist = "0.36.0"
androidx-activity-compose = "1.9.2"
androidx-activity-core = "1.9.2"
androidx-annotation = "1.8.2"
androidx-composeBom = "2024.09.02"
androidx-datastore = "1.1.1"
androidx-junit = "1.2.1"
androidx-lifecycle = "2.8.6"
androidx-navigation = "2.8.1"
androidx-other-appCompat = "1.7.0"
androidx-other-browser = "1.8.0"
androidx-other-constraintLayout = "2.1.4"
androidx-other-core = "1.13.1"
androidx-other-splashscreen = "1.2.0-alpha02"
androidx-other-startup = "1.2.0"
androidx-other-workManager = "2.9.1"
androidx-profileInstaller = "1.4.0"
androidx-test = "1.6.1"
androidx-testRunners = "1.6.2"
androidxGraphicsShapes = "1.0.1"
arrow = "1.2.4"
assertK = "0.28.1"
coil = "2.7.0"
composeRichtext = "1.0.0-alpha01"
concatAdapterExtension = "1.2.1"
coreLibraryDesugaring = "2.1.2"
coroutines = "1.9.0"
datadog = "2.13.1"
dependencyAnalysis = "2.1.0"
firebaseCrashlyticsBuildtools = "3.0.2"
hedvigAuthlib = "1.3.20"
junit = "4.13.2"
koinBom = "3.5.6"
kotlinx-serialization = "1.7.3"
kotlinxDatetime = "0.6.1"
leakCanary = "2.14"
modalSheet = "0.7.0"
moneta = "1.4.4"
navigationRecentsUrlSharing = "1.0.0"
okhttp = "4.12.0"
okio = "3.9.1"
paging = "3.3.2"
playReview = "2.0.1"
playServicesBase = "18.5.0"
retrofit = "2.11.0"
retrofitArrow = "1.2.4"
robolectric = "4.13"
room = "2.7.0-alpha08"
slimber = "2.0.0"
sqlite = "2.5.0-alpha08"
testParameterInjector = "1.17"
timber = "5.0.1"
turbine = "1.1.0"
unleash = "1.0.0"
uuid = "0.8.4"
zXing = "3.5.3"
zoomable = "1.6.2"

[libraries]

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-activity-core = { module = "androidx.activity:activity", version.ref = "androidx-activity-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-compose-animation = { module = "androidx.compose.animation:animation-core" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundationLayout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-materialIconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-materialRipple = { module = "androidx.compose.material:material-ripple" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-uiCore = { module = "androidx.compose.ui:ui" }
androidx-compose-uiGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-uiUnit = { module = "androidx.compose.ui:ui-unit" }
androidx-compose-uiUtil = { module = "androidx.compose.ui:ui-util" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preferencesCore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-graphicsShapes = { module = "androidx.graphics:graphics-shapes", version.ref = "androidxGraphicsShapes" }
androidx-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-junit" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "androidx-navigation" }
androidx-other-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-other-appCompat" }
androidx-other-browser = { module = "androidx.browser:browser", version.ref = "androidx-other-browser" }
androidx-other-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-other-constraintLayout" }
androidx-other-core = { module = "androidx.core:core-ktx", version.ref = "androidx-other-core" }
androidx-other-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-other-splashscreen" }
androidx-other-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-other-startup" }
androidx-other-workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-other-workManager" }
androidx-profileInstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileInstaller" }
androidx-test = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-testRunners = { module = "androidx.test:runner", version.ref = "androidx-testRunners" }
apollo-adapters-datetime = { module = "com.apollographql.adapters:apollo-adapters-kotlinx-datetime", version.ref = "apolloAdapters" }
apollo-annotations = { module = "com.apollographql.apollo:apollo-annotations", version.ref = "apollo" }
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }
apollo-normalizedCache = { module = "com.apollographql.apollo:apollo-normalized-cache", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-testingSupport = { module = "com.apollographql.apollo:apollo-testing-support", version.ref = "apollo" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
assertK = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertK" }
coil-coil = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
compose-richtext = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "composeRichtext" }
compose-richtextUi = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "composeRichtext" }
compose-richtextMarkdown = { module = "com.halilibo.compose-richtext:richtext-markdown", version.ref = "composeRichtext" }
concatAdapterExtension = { module = "com.github.carousell:ConcatAdapterExtension", version.ref = "concatAdapterExtension" }
coreLibraryDesugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "coreLibraryDesugaring" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datadog-sdk-compose = { module = "com.datadoghq:dd-sdk-android-compose", version.ref = "datadog" }
datadog-sdk-core = { module = "com.datadoghq:dd-sdk-android-core", version.ref = "datadog" }
datadog-sdk-logs = { module = "com.datadoghq:dd-sdk-android-logs", version.ref = "datadog" }
datadog-sdk-okhttp = { module = "com.datadoghq:dd-sdk-android-okhttp", version.ref = "datadog" }
datadog-sdk-rum = { module = "com.datadoghq:dd-sdk-android-rum", version.ref = "datadog" }
datadog-sdk-trace = { module = "com.datadoghq:dd-sdk-android-trace", version.ref = "datadog" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = "com.google.firebase:firebase-bom:33.3.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-dynamicLinks = { module = "com.google.firebase:firebase-dynamic-links" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
hedvig-authlib = { module = "com.hedvig.authlib:authlib", version.ref = "hedvigAuthlib" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom"  }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-workManager = { module = "io.insert-koin:koin-androidx-workmanager" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
material-components = { module = "com.google.android.material:material", version = "1.12.0" }
modal-sheet = { module = "io.github.oleksandrbalan:modalsheet", version.ref = "modalSheet" }
molecule = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }
moneta = { module = "org.javamoney.moneta:moneta-core", version.ref = "moneta" }
navigationRecentsUrlSharing = { module = "com.stylianosgakis.navigation.recents.url.sharing:navigation-recents-url-sharing", version.ref = "navigationRecentsUrlSharing" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
playReview = { module = "com.google.android.play:review-ktx", version.ref = "playReview" }
playServicesBase = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitArrow = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "retrofitArrow" }
retrofitKotlinxSerializationConverter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-ksp = { module = "androidx.room:room-compiler", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
slimber = { module = "com.github.PaulWoitaschek:Slimber", version.ref = "slimber" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParameterInjector" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
unleash = { module = "io.getunleash:unleash-android-proxy-sdk", version.ref = "unleash" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
zXing = { module = "com.google.zxing:core", version.ref = "zXing" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
# Plugin libraries for build-logic's convention plugins to use to resolve the types/tasks coming from these plugins
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
apollo-gradlePlugin = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
compose-compilerGradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin"}
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradlePlugin = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }

# lint dependencies
lintApi = { module = "com.android.tools.lint:lint-api", version.ref = "lintApi" }

[bundles]

[plugins]

androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
appIconBannerGenerator = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }
composeCompilerGradlePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
datadog = { id = "com.datadoghq.dd-sdk-android-gradle-plugin", version.ref = "datadogPlugin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
license = { id = "com.jaredsburrows.license", version.ref = "license" }
lintGradlePlugin = { id = "com.android.lint", version.ref = "lintGradlePlugin" }
room = { id = "androidx.room", version.ref = "room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
squareSortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "squareSortDependencies" }
