[versions]
# androidSdkVersions
compileSdkVersion = "36"
targetSdkVersion = "35"
minSdkVersion = "23"

# lint versions
lintApi = "31.12.0"
lintGradlePlugin = "8.12.0"

# gradlePlugin versions
androidGradlePlugin = "8.12.0"
apollo = "4.3.2"
apolloAdapters = "0.7.0"
cacheFix = "3.0.1"
crashlytics = "3.0.6"
datadogPlugin = "1.18.0"
doctor = "0.11.0"
easylauncher = "6.4.1"
googleServices = "4.4.3"
gradleDevelocity = "4.1"
kotlin = "2.2.0"
kotlinter = "5.2.0"
ksp = "2.2.0-2.0.2"
ktor = "3.2.3"
license = "0.9.8"
molecule = "2.1.0"
skie = "0.10.5"
squareSortDependencies = "0.14"

# Other versions sorted alphabetically
accompanist = "0.37.3"
androidx-activity-compose = "1.10.1"
androidx-activity-core = "1.10.1"
androidx-annotation = "1.9.1"
androidx-composeBom = "2025.07.00"
androidx-datastore = "1.1.7"
androidx-junit = "1.3.0"
androidx-lifecycle = "2.9.2"
androidx-navigation = "2.9.3"
androidx-other-appCompat = "1.7.1"
androidx-other-browser = "1.9.0"
androidx-other-constraintLayout = "2.2.0"
androidx-other-core = "1.16.0"
androidx-other-splashscreen = "1.2.0-rc01"
androidx-other-startup = "1.2.0"
androidx-other-workManager = "2.10.3"
androidx-test = "1.7.0"
androidx-testRunners = "1.7.0"
androidx-ui-alpha = "1.8.3"
androidxGraphicsShapes = "1.0.1"
jetbrains-compose-runtime = "1.8.2"
arrow = "2.1.2"
assertK = "0.28.1"
atomicfu = "0.29.0"
coil = "2.7.0"
composeRichtext = "1.0.0-alpha03"
coreLibraryDesugaring = "2.1.5"
coroutines = "1.10.2"
datadog = "2.25.0"
dependencyAnalysis = "2.19.0"
firebaseCrashlyticsBuildtools = "3.0.6"
junit = "4.13.2"
koinBom = "4.1.0"
kotlinx-serialization = "1.9.0"
kotlinxDatetime = "0.7.1-0.6.x-compat"
media3 = "1.8.0"
modalSheet = "0.7.0"
moneta = "1.4.4"
navigationRecentsUrlSharing = "1.0.0"
okhttp = "4.12.0"
okio = "3.16.0"
paging = "3.3.6"
playReview = "2.0.2"
playServicesBase = "18.7.2"
retrofit = "3.0.0"
robolectric = "4.15.1"
room = "2.7.2"
slimber = "2.0.0"
sqlite = "2.5.2"
testParameterInjector = "1.18"
timber = "5.0.1"
turbine = "1.2.1"
unleash = "0.5.9"
uuid = "0.8.4"
zXing = "3.5.3"
zoomable = "1.7.0"

[libraries]

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-activity-core = { module = "androidx.activity:activity", version.ref = "androidx-activity-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-animationCore = { module = "androidx.compose.animation:animation-core" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundationLayout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-materialIconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-materialRipple = { module = "androidx.compose.material:material-ripple" }
androidx-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose-runtime" }
androidx-compose-runtimeSaveable = { module = "androidx.compose.runtime:runtime-saveable" }

androidx-compose-uiCore = { module = "androidx.compose.ui:ui", version.ref = "androidx-ui-alpha" }
androidx-compose-uiText = { module = "androidx.compose.ui:ui-text", version.ref = "androidx-ui-alpha" }
androidx-compose-uiGraphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-ui-alpha" }
androidx-compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-ui-alpha" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-ui-alpha" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-ui-alpha" }
androidx-compose-uiUnit = { module = "androidx.compose.ui:ui-unit", version.ref = "androidx-ui-alpha" }
androidx-compose-uiUtil = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-ui-alpha" }

androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preferencesCore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-graphicsShapes = { module = "androidx.graphics:graphics-shapes", version.ref = "androidxGraphicsShapes" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "androidx-navigation" }
androidx-other-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-other-appCompat" }
androidx-other-browser = { module = "androidx.browser:browser", version.ref = "androidx-other-browser" }
androidx-other-core = { module = "androidx.core:core", version.ref = "androidx-other-core" }
androidx-other-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-other-core" }
androidx-other-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-other-splashscreen" }
androidx-other-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-other-startup" }
androidx-other-workManager = { module = "androidx.work:work-runtime", version.ref = "androidx-other-workManager" }
androidx-test = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-testRunners = { module = "androidx.test:runner", version.ref = "androidx-testRunners" }
apollo-adapters-core = { module = "com.apollographql.adapters:apollo-adapters-core", version.ref = "apolloAdapters" }
apollo-adapters-datetime = { module = "com.apollographql.adapters:apollo-adapters-kotlinx-datetime", version.ref = "apolloAdapters" }
apollo-annotations = { module = "com.apollographql.apollo:apollo-annotations", version.ref = "apollo" }
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }
apollo-normalizedCache = { module = "com.apollographql.apollo:apollo-normalized-cache", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-testingSupport = { module = "com.apollographql.apollo:apollo-testing-support", version.ref = "apollo" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
assertK = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertK" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
coil-coil = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
compose-richtext = { module = "com.halilibo.compose-richtext:richtext-ui", version.ref = "composeRichtext" }
compose-richtextCommonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "composeRichtext" }
compose-richtextMaterial = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "composeRichtext" }
coreLibraryDesugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "coreLibraryDesugaring" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datadog-sdk-compose = { module = "com.datadoghq:dd-sdk-android-compose", version.ref = "datadog" }
datadog-sdk-core = { module = "com.datadoghq:dd-sdk-android-core", version.ref = "datadog" }
datadog-sdk-logs = { module = "com.datadoghq:dd-sdk-android-logs", version.ref = "datadog" }
datadog-sdk-okhttp = { module = "com.datadoghq:dd-sdk-android-okhttp", version.ref = "datadog" }
datadog-sdk-rum = { module = "com.datadoghq:dd-sdk-android-rum", version.ref = "datadog" }
datadog-sdk-trace = { module = "com.datadoghq:dd-sdk-android-trace", version.ref = "datadog" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = "com.google.firebase:firebase-bom:34.1.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-coreViewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
koin-coreViewmodelNavigation = { module = "io.insert-koin:koin-core-viewmodel-navigation" }
koin-workManager = { module = "io.insert-koin:koin-androidx-workmanager" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
modal-sheet = { module = "io.github.oleksandrbalan:modalsheet", version.ref = "modalSheet" }
molecule = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }
navigationRecentsUrlSharing = { module = "com.stylianosgakis.navigation.recents.url.sharing:navigation-recents-url-sharing", version.ref = "navigationRecentsUrlSharing" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
playReview = { module = "com.google.android.play:review", version.ref = "playReview" }
playServicesBase = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitArrow = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "arrow" }
retrofitKotlinxSerializationConverter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-ksp = { module = "androidx.room:room-compiler", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
slimber = { module = "com.github.PaulWoitaschek:Slimber", version.ref = "slimber" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParameterInjector" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
unleash = { module = "io.getunleash:unleash-android-proxy-sdk", version.ref = "unleash" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
zXing = { module = "com.google.zxing:core", version.ref = "zXing" }
zoomable = { module = "com.mxalbert.zoomable:zoomable", version.ref = "zoomable" }
# Plugin libraries for build-logic's convention plugins to use to resolve the types/tasks coming from these plugins
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidMultiplatform-gradlePlugin = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidGradlePlugin" }
apollo-gradlePlugin = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
compose-compilerGradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradlePlugin = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
room-gradlePlugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

# lint dependencies
lintApi = { module = "com.android.tools.lint:lint-api", version.ref = "lintApi" }

# temporary bug workaround
androidx-kmp-preview-bug1-workaround = { module = "androidx.customview:customview-poolingcontainer", version = "1.1.0" }
androidx-kmp-preview-bug2-workaround = { module = "androidx.emoji2:emoji2", version = "1.5.0" }

[bundles]
kmpPreviewBugWorkaround = ["androidx-kmp-preview-bug1-workaround", "androidx-kmp-preview-bug2-workaround"]

[plugins]

androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidLibraryMultiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
appIconBannerGenerator = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }
composeCompilerGradlePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
datadog = { id = "com.datadoghq.dd-sdk-android-gradle-plugin", version.ref = "datadogPlugin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
gradleDevelocity = { id = "com.gradle.develocity", version.ref = "gradleDevelocity" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
license = { id = "com.jaredsburrows.license", version.ref = "license" }
lintGradlePlugin = { id = "com.android.lint", version.ref = "lintGradlePlugin" }
room = { id = "androidx.room", version.ref = "room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
squareSortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "squareSortDependencies" }
