[versions]
# androidSdkVersions
compileSdkVersion = "33"
targetSdkVersion = "33"
minSdkVersion = "23"

# gradlePlugin versions
androidGradlePlugin = "8.0.2"
androidRemoveUnusedResourcesPlugin = "1.4.1"
apollo = "3.8.2"
cacheFix = "2.7.2"
crashlytics = "2.9.7"
datadogPlugin = "1.9.0"
doctor = "0.8.1"
easylauncher = "6.2.0"
googleServices = "4.3.15"
kotlin = "1.8.21"
kotlinter = "3.12.0"
ktor = "2.3.1"
license = "0.9.3"

# Other versions sorted alphabetically
accompanist = "0.30.1"
adyen = "4.12.1"
androidx-annotation = "1.6.0"
androidx-arch-testing = "2.2.0"
androidx-composeBom = "2023.06.01"
androidx-composeCompiler = "1.4.7"
androidx-datastore = "1.0.0"
androidx-espresso = "3.5.1"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.6.0"
androidx-other-activityCompose = "1.7.2"
androidx-other-appCompat = "1.6.1"
androidx-other-browser = "1.5.0"
androidx-other-constraintLayout = "2.1.4"
androidx-other-core = "1.10.1"
androidx-other-dynamicAnimation = "1.0.0"
androidx-other-fragment = "1.6.0"
androidx-other-preference = "1.2.0"
androidx-other-recyclerView = "1.3.0"
androidx-other-splashscreen = "1.0.1"
androidx-other-startup = "1.1.1"
androidx-other-swipeRefreshLayout = "1.1.0"
androidx-other-transition = "1.4.1"
androidx-other-viewPager2 = "1.0.0"
androidx-other-workManager = "2.8.1"
androidx-profileInstaller = "1.3.1"
androidx-test-junit = "1.1.5"
androidx-test-rules = "1.5.0"
androidx-test-runner = "1.5.2"
arrow = "1.2.0-RC"
assertK = "0.26.1"
coil = "2.4.0"
concatAdapterExtension = "1.2.1"
coreLibraryDesugaring = "2.0.3"
coroutines = "1.7.2"
datadog = "1.19.3"
dependencyAnalysis = "1.20.0"
firebase = "28.4.2"
flexbox = "3.0.0"
fragmentViewBindingDelegate = "1.0.2"
hAnalytics = "v0.300.0"
hedvigAuthlib = "1.2"
insetter = "0.6.1"
jsonTest = "20230618"
junit = "4.13.2"
kaspresso = "1.5.2"
kiwi-navigationCompose = "0.6.2"
koinAndroid = "3.4.1"
koinCompose = "3.4.5"
koinCore = "3.4.1"
kotlinx-serialization = "1.5.1"
kotlinxDatetime = "0.4.0"
kotlinxImmutableCollections = "0.3.5"
leakCanary = "2.12"
markwon = "4.6.2"
materialComponents = "1.9.0"
mockk = "1.13.5"
moneta = "1.4.2"
okhttp = "4.11.0"
okio = "3.4.0"
playReview = "2.0.1"
reactiveX-Android = "2.1.1"
reactiveX-Kotlin = "2.4.0"
retrofit = "2.9.0"
retrofitArrow = "1.2.0-RC"
retrofitKotlinxSerializationConverter = "1.0.0"
shimmer = "0.5.0"
slimber = "2.0.0"
timber = "5.0.1"
turbine = "1.0.0"
zXing = "3.5.1"

[libraries]

accompanist-insetsUi = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigationAnimation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
adyen = { module = "com.adyen.checkout:drop-in", version.ref = "adyen" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-arch-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-testing" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundationLayout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-materialIconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-uiCore = { module = "androidx.compose.ui:ui" }
androidx-compose-uiUnit = { module = "androidx.compose.ui:ui-unit" }
androidx-compose-uiTestJunit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-uiUtil = { module = "androidx.compose.ui:ui-util" }
androidx-compose-uiViewBinding = { module = "androidx.compose.ui:ui-viewbinding" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferencesCore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-espresso" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-espresso" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "androidx-navigation" }
androidx-other-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-other-activityCompose" }
androidx-other-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-other-appCompat" }
androidx-other-browser = { module = "androidx.browser:browser", version.ref = "androidx-other-browser" }
androidx-other-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-other-constraintLayout" }
androidx-other-core = { module = "androidx.core:core-ktx", version.ref = "androidx-other-core" }
androidx-other-dynamicAnimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "androidx-other-dynamicAnimation" }
androidx-other-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-other-fragment" }
androidx-other-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-other-preference" }
androidx-other-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-other-recyclerView" }
androidx-other-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-other-splashscreen" }
androidx-other-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-other-startup" }
androidx-other-swipeRefreshLayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-other-swipeRefreshLayout" }
androidx-other-transition = { module = "androidx.transition:transition-ktx", version.ref = "androidx-other-transition" }
androidx-other-viewPager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-other-viewPager2" }
androidx-other-workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-other-workManager" }
androidx-profileInstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileInstaller" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
apollo-adapters = { module = "com.apollographql.apollo3:apollo-adapters", version.ref = "apollo" }
apollo-api = { module = "com.apollographql.apollo3:apollo-api", version.ref = "apollo" }
apollo-idlingResource = { module = "com.apollographql.apollo3:apollo-idling-resource", version.ref = "apollo" }
apollo-mockServer = { module = "com.apollographql.apollo3:apollo-mockserver", version.ref = "apollo" }
apollo-normalizedCache = { module = "com.apollographql.apollo3:apollo-normalized-cache", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-testingSupport = { module = "com.apollographql.apollo3:apollo-testing-support", version.ref = "apollo" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
assertK = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertK" }
coil-coil = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
concatAdapterExtension = { module = "com.github.carousell:ConcatAdapterExtension", version.ref = "concatAdapterExtension" }
coreLibraryDesugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "coreLibraryDesugaring" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datadog-sdk = { module = "com.datadoghq:dd-sdk-android", version.ref = "datadog" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = "com.google.firebase:firebase-bom:32.2.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-dynamicLinks = { module = "com.google.firebase:firebase-dynamic-links" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-playServicesBase = { module = "com.google.android.gms:play-services-base" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
fragmentViewBindingDelegate = { module = "com.github.Zhuinden:fragmentviewbindingdelegate-kt", version.ref = "fragmentViewBindingDelegate" }
hAnalytics = { module = "com.github.HedvigInsurance:hAnalytics", version.ref = "hAnalytics" }
hedvig-authlib = { module = "com.hedvig.authlib:authlib", version.ref = "hedvigAuthlib" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
jsonTest = { module = "org.json:json", version.ref = "jsonTest" }
junit = { module = "junit:junit", version.ref = "junit" }
kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspresso" }
kiwi-navigationCompose = { module = "com.kiwi.navigation-compose.typed:core", version.ref = "kiwi-navigationCompose" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinCore" }
koin-workManager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinCore" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxImmutableCollections" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
materialComponents = { module = "com.google.android.material:material", version.ref = "materialComponents" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-jvm = { module = "io.mockk:mockk", version.ref = "mockk" }
moneta = { module = "org.javamoney.moneta:moneta-core", version.ref = "moneta" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
playReview = { module = "com.google.android.play:review-ktx", version.ref = "playReview" }
reactiveX-android = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "reactiveX-Android" }
reactiveX-kotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "reactiveX-Kotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitArrow = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "retrofitArrow" }
retrofitKotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
slimber = { module = "com.github.PaulWoitaschek:Slimber", version.ref = "slimber" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
zXing = { module = "com.google.zxing:core", version.ref = "zXing" }

# Plugin libraries for build-logic's convention plugins to use to resolve the types/tasks coming from these plugins
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
apollo-gradlePlugin = { module = "com.apollographql.apollo3:apollo-gradle-plugin", version.ref = "apollo" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradlePlugin = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }

[bundles]

[plugins]

androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
appIconBannerGenerator = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
datadog = { id = "com.datadoghq.dd-sdk-android-gradle-plugin", version.ref = "datadogPlugin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
license = { id = "com.jaredsburrows.license", version.ref = "license" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidRemoveUnusedResourcesPlugin = { id = "io.github.irgaly.remove-unused-resources", version.ref = "androidRemoveUnusedResourcesPlugin" }
